### ISSUE TITLE
bot cant start

### ISSUE THREAD

**Issue by ghost** [KSJaay/Alita#16]
What exactly cause this bug?? and how could we reproduce it??
Starting the bot

Command:
npm start index.js

**Screenshots**
![yhingg](https://user-images.githubusercontent.com/60261412/126921403-41fdf3d1-3d35-47f6-a8a5-abe112c75169.png)

**Additional context**

Alita version:
latest as of im writing
Discord.js version:
no idea, just did npm i
Node.js verstion:
no idea, just did sudo apt-get install nodejs
Operating System:
Ubuntu 20.04

The thing that happens when i do it tho, is this

Unknown error occured:

/home/eddippla/Downloads/Alita-master/node_modules/some-random-cat/src/Util.js:8
    static info = {
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/eddippla/Downloads/Alita-master/node_modules/some-random-cat/index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    
    Also, if this does anything, i renamed Alita.js to index.js, i was having the error before this tho

**Comment by KSJaay** [comment]
I tried to recreate the issue but was unable to. Can you try to update your version of some-random-cat and see if that works
