### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jonzmuda** [KSJaay/Alita#20]
`Unable to connect to MongoDB Database.
Error: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
MongooseError: Operation `guilds.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\jonzm\OneDrive\Desktop\Alita-master\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
MongooseError: Operation `guilds.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\jonzm\OneDrive\Desktop\Alita-master\node_modules\mongoose\lib\drivers\node-mongodb-native\-mongodb-native\collection.js:185:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
MongooseError: Operation `guilds.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\jonzm\OneDrive\Desktop\Alita-master\node_modules\mongoose\lib\drivers\node-mongodb-native\-mongodb-native\collection.js:185:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)`

**Comment by KSJaay** [comment]
Do you have MongoDB server installed on your current device??

**Comment by jonzmuda** [comment]
I do. I'm fairly new to coding and very new to databases so I think I might
have set it up incorrectly. Is there a tutorial I can use for this bot in
specific?

**Comment by jonzmuda** [comment]
In my `config.json` file, what should I change ` "mongoDB": "mongodb://localhost:27017/AlitaBot",` to?

**Comment by KSJaay** [comment]
Hey sorry I been busy, if you haven't figured this out check out this guide for how to install MongoDB locally: https://medium.com/@LondonAppBrewery/how-to-download-install-mongodb-on-windows-4ee4b3493514
Only follow till the end of step 2 if you're using windows and then you can also install MongoDB compass from: https://www.mongodb.com/try/download/compass
Which you can use to connect to the database and create documents.

In config as long as you have set up the database correctly it'll connect using that information and you shouldn't need to change it.
